// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// iGess
RcppExport SEXP iGess(arma::fmat& X, arma::vec& y, SEXP Z, SEXP SS, SEXP opts);
RcppExport SEXP IGESS_iGess(SEXP XSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP SSSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(iGess(X, y, Z, SS, opts));
    return rcpp_result_gen;
END_RCPP
}
// iGessCV
RcppExport SEXP iGessCV(arma::fmat& X, arma::vec& y, SEXP Z, SEXP SS, SEXP opts);
RcppExport SEXP IGESS_iGessCV(SEXP XSEXP, SEXP ySEXP, SEXP ZSEXP, SEXP SSSEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::fmat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< SEXP >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< SEXP >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(iGessCV(X, y, Z, SS, opts));
    return rcpp_result_gen;
END_RCPP
}
// iGessPlink
RcppExport SEXP iGessPlink(Rcpp::String genoplinkfile, Rcpp::String summaryfile, Rcpp::String configfile);
RcppExport SEXP IGESS_iGessPlink(SEXP genoplinkfileSEXP, SEXP summaryfileSEXP, SEXP configfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type genoplinkfile(genoplinkfileSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type summaryfile(summaryfileSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type configfile(configfileSEXP);
    rcpp_result_gen = Rcpp::wrap(iGessPlink(genoplinkfile, summaryfile, configfile));
    return rcpp_result_gen;
END_RCPP
}
// iGessPlinkCV
RcppExport SEXP iGessPlinkCV(Rcpp::String genoplinkfile, Rcpp::String summaryfile, Rcpp::String configfile);
RcppExport SEXP IGESS_iGessPlinkCV(SEXP genoplinkfileSEXP, SEXP summaryfileSEXP, SEXP configfileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type genoplinkfile(genoplinkfileSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type summaryfile(summaryfileSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type configfile(configfileSEXP);
    rcpp_result_gen = Rcpp::wrap(iGessPlinkCV(genoplinkfile, summaryfile, configfile));
    return rcpp_result_gen;
END_RCPP
}
// read_data
RcppExport SEXP read_data(Rcpp::String genoplinkfile, SEXP summaryfile_, SEXP configfile_);
RcppExport SEXP IGESS_read_data(SEXP genoplinkfileSEXP, SEXP summaryfile_SEXP, SEXP configfile_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type genoplinkfile(genoplinkfileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type summaryfile_(summaryfile_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type configfile_(configfile_SEXP);
    rcpp_result_gen = Rcpp::wrap(read_data(genoplinkfile, summaryfile_, configfile_));
    return rcpp_result_gen;
END_RCPP
}
// iGessPredict
RcppExport SEXP iGessPredict(SEXP fit_, arma::mat& X, SEXP Z);
RcppExport SEXP IGESS_iGessPredict(SEXP fit_SEXP, SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fit_(fit_SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(iGessPredict(fit_, X, Z));
    return rcpp_result_gen;
END_RCPP
}
// calaucRcpp
double calaucRcpp(arma::vec label, arma::vec pred);
RcppExport SEXP IGESS_calaucRcpp(SEXP labelSEXP, SEXP predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type label(labelSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pred(predSEXP);
    rcpp_result_gen = Rcpp::wrap(calaucRcpp(label, pred));
    return rcpp_result_gen;
END_RCPP
}
