# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' IGESS
#' @description
#' IGESS Model Training
#'
#' @param X  a N by P matrix of the genotype data, N-sample size, P - SNPs number
#'
#' @param y  a N by 1 matrix of the phenotypes
#'
#' @param Z  a N by M(number of covariates) matrix, the covariates of the N individuals, set to NULL by default
#' @param SS  a K by P matrix for summary statistics, set to NULL by default
#' @param opts  a list with fields(max_iter, display_gap), NULL corresponds to list(max_iter=600, display_gap = 60)
#'
#' @return List of model parameters, refer to \code{wrap_fit} function in Rcpp_auc.hpp for the fields
#'
#' @examples
#' ##Working with no summary statistics, no covariates and options
#' data(IGESSDB)
#' fit <- iGess(Model$X,Model$y)
#'
#'
#' #Working with summary statistics(p-values) and no covariates
#' data(IGESSDB)
#' fit <- iGess(Model$X, Model$y, NULL, Model$AIPVal)
#'
#' #Options Specified
#' data(IGESSDB)
#' opts = list(max_iter=600, display_gap = 100)
#' fit <- iGess(X,y,NULL,SS,opts)
#'
#' @details
#' \code{iGess} fits the iGess model. It requires to provide genotype matrix \code{X}
#' and phenotype matrix \code{y}, while users can also provide covariates data to \code{Z},
#' the summary statistics to \code{SS}, and the settings to \code{opts}.  these last three
#' parameters \code{Z}, \code{SS},\code{opts} could be set to NULL.
#' @export
iGess <- function(X, y, Z = NULL, SS = NULL, opts = NULL) {
    .Call('IGESS_iGess', PACKAGE = 'IGESS', X, y, Z, SS, opts)
}

#' @title
#' IGESSCV
#' @description
#' evaluating the performance of prediction by cross validation
#'
#' @param X  a N by P matrix of the genotype data, N-sample size, P - SNPs number
#'
#' @param y  a N by 1 matrix of the phenotypes
#'
#' @param Z  a N by M(number of covariates) matrix, the covariates of the N individuals, set to NULL by default
#' @param SS  a K by P matrix for summary statistics, set to NULL by default
#' @param opts  a list with fields(max_iter, display_gap), NULL corresponds to list(max_iter=600, display_gap = 60, n_fold = 5)
#'
#' @return list(auc, cor), auc is for the case-control studies, cor is for quantitative trait studies
#'
#' @examples
#' ##Working with no summary statistics, no covariates and options
#' data(IGESSDB)
#' pair <- iGessCV(Model$X,Model$y)
#'
#'
#' #Working with summary statistics(p-values) and no covariates
#' data(IGESSDB)
#' pair <- iGessCV(Model$X, Model$y, NULL, Model$AIPVal)
#'
#' #Options Specified
#' data(IGESSDB)
#' opts = list(max_iter=600, display_gap = 100)
#' pair <- iGessCV(X,y,NULL,SS,opts)
#'
#' @details
#' \code{iGessCV} evaluating the performance of prediction by cross validation.
#' It requires to provide genotype matrix \code{X}
#' and phenotype matrix \code{y}, while users can also provide covariates data to \code{Z},
#' the summary statistics to \code{SS}, and the settings to \code{opts}.  these last three
#' parameters \code{Z}, \code{SS},\code{opts} could be set to NULL.
#' @export
iGessCV <- function(X, y, Z = NULL, SS = NULL, opts = NULL) {
    .Call('IGESS_iGessCV', PACKAGE = 'IGESS', X, y, Z, SS, opts)
}

#' @title
#' iGessPlink
#' @description
#' IGESS Model Training with plink binary file and summary statistics file
#'
#' @param genoplinkfile  the plink file for the genotype data
#'
#' @param summaryfile  the summary statistics file for the p-values
#'
#' @param configfile  the config file for summary statistics to specify the columns of pvalues
#'
#' @return List of model parameters, refer to \code{wrap_fit} function in Rcpp_auc.hpp for the fields
#'
#' @examples
#' # file name and its format
#' # the required binary files are CD.bed, CD.bim, CD.fam, \code{genoplinkfile} should be \code{CD} in its own directory.
#' # for \code{summaryfile}, take the headers below for example
#' CHR SNP POS major_al minor_al wtccc_info narac1_info narac2_info eira_info canada_info brass_info
#' wtccc_z narac1_z narac2_z eira_z canada_z brass_z cases_MM cases_Mm cases_mm controls_MM controls_Mm
#' controls_mm meta_OR OR_95%CI_lo OR_95%CI_up meta_z meta_2tP CochranQ Q_Pval
#'
#' #we should specify the column names for the summary statistics required and the column names for chromsome and the SNP name
#'
#' #the content of \code{configfile} is like following
#' zvalue=narac1_z,canada_z,brass_z
#' snp=SNP
#' chr=CHR
#'
#' #zvalue should be replaced by pvalue if p-values are provided
#'
#'
#'
#' #Working with no summary statistics
#' iGessPlink(genoplinkfile)
#'
#'
#' #Working with summary statistics
#' iGessPlink(genoplinkfile, summaryfile, configfile)
#'
#'
#' @details
#' \code{iGessPlink} fits the iGess model. It requires to provide binary plink file name to \code{genoplinkfile}, the binary file
#' should be SNP-major type in the current version of IGESS, while the users can also provide
#' summary statistics file name to \code{summaryfile},
#' the config file \code{configfile} is a must when \code{summaryfile} is provided.
#'
#' \code{iGessPlink} take the overlap of genotype data and summary statistics with respect to the SNPs
#'
#' @export
iGessPlink <- function(genoplinkfile, summaryfile, configfile) {
    .Call('IGESS_iGessPlink', PACKAGE = 'IGESS', genoplinkfile, summaryfile, configfile)
}

#' @title
#' iGessPlinkCV
#' @description
#' evaluating the performance of prediction by cross validation with plink binary file and summary statistics file
#'
#' @param genoplinkfile  the plink file for the genotype data
#'
#' @param summaryfile  the summary statistics file for the p-values
#'
#' @param configfile  the config file for summary statistics to specify the columns of pvalues
#'
#' @return list(auc, cor), auc is for the case-control studies, cor is for quantitative trait studies
#' @examples
#' # file name and its format
#' # the required binary files are CD.bed, CD.bim, CD.fam, \code{genoplinkfile} should be \code{CD} in its own directory.
#' # for \code{summaryfile}, take the headers below for example
#' CHR SNP POS major_al minor_al wtccc_info narac1_info narac2_info eira_info canada_info brass_info
#' wtccc_z narac1_z narac2_z eira_z canada_z brass_z cases_MM cases_Mm cases_mm controls_MM controls_Mm
#' controls_mm meta_OR OR_95%CI_lo OR_95%CI_up meta_z meta_2tP CochranQ Q_Pval
#'
#' #we should specify the column names for the summary statistics required and the column names for chromsome and the SNP name
#'
#' #the content of \code{configfile} is like following
#' zvalue=narac1_z,canada_z,brass_z
#' snp=SNP
#' chr=CHR
#'
#' #zvalue should be replaced by pvalue if p-values are provided
#'
#'
#'
#' #Working with no summary statistics
#' iGessPlink(genoplinkfile)
#'
#'
#' #Working with summary statistics
#' iGessPlink(genoplinkfile, summaryfile, configfile)
#'
#'
#' @details
#' \code{iGessPlinkCV} evaluating the performance of prediction by cross validation. It requires to provide binary plink file name to \code{genoplinkfile}, the binary file
#' should be SNP-major type in the current version of IGESS, while the users can also provide
#' summary statistics file name to \code{summaryfile},
#' the config file \code{configfile} is a must when \code{summaryfile} is provided.
#'
#' \code{iGessPlinkCV} take the overlap of genotype data and summary statistics with respect to the SNPs
#'
#' @export
iGessPlinkCV <- function(genoplinkfile, summaryfile, configfile) {
    .Call('IGESS_iGessPlinkCV', PACKAGE = 'IGESS', genoplinkfile, summaryfile, configfile)
}

#' @title
#' read_data
#' @description
#' read the binary plink file or correpsonding summary statistics file into objects
#'
#' @param genoplinkfile  the plink file for the genotype data
#'
#' @param summaryfile  the summary statistics file for the p-values
#'
#' @param configfile  the config file for summary statistics to specify the columns of pvalues
#'
#' @return list(X, y) - genotype data and its phenotypes or list(X,y,pvalues) - X, y and its corresponding pvalues
#' @examples
#' # file name and its format
#' # the required binary files are CD.bed, CD.bim, CD.fam, \code{genoplinkfile} should be \code{CD} in its own directory.
#' # for \code{summaryfile}, take the headers below for example
#' CHR SNP POS major_al minor_al wtccc_info narac1_info narac2_info eira_info canada_info brass_info
#' wtccc_z narac1_z narac2_z eira_z canada_z brass_z cases_MM cases_Mm cases_mm controls_MM controls_Mm
#' controls_mm meta_OR OR_95%CI_lo OR_95%CI_up meta_z meta_2tP CochranQ Q_Pval
#'
#' #we should specify the column names for the summary statistics required and the column names for chromsome and the SNP name
#'
#' #the content of \code{configfile} is like following
#' zvalue=narac1_z,canada_z,brass_z
#' snp=SNP
#' chr=CHR
#'
#' #zvalue should be replaced by pvalue if p-values are provided
#'
#' #Working with no summary statistics
#' read_data(genoplinkfile)
#'
#'
#' #Working with summary statistics
#' read_data(genoplinkfile, summaryfile, configfile)
#'
#'
#' @details
#' \code{read_data} evaluating the performance of prediction by cross validation. It requires to provide binary plink file name to \code{genoplinkfile}, the binary file
#' should be SNP-major type in the current version of IGESS, while the users can also provide
#' summary statistics file name to \code{summaryfile},
#' the config file \code{configfile} is a must when \code{summaryfile} is provided.
#'
#' \code{read_data} take the overlap of genotype data and summary statistics with respect to the SNPs
#'
#' @export
read_data <- function(genoplinkfile, summaryfile_ = NULL, configfile_ = NULL) {
    .Call('IGESS_read_data', PACKAGE = 'IGESS', genoplinkfile, summaryfile_, configfile_)
}

#' @title
#' iGessPredict
#' @description
#' predict the output of the given X and Covariates
#'
#' @param fit  List of the IGESSfit fields
#'
#' @param X  the given data matrix
#'
#' @param Z  covariates, set to be NULL by default
#'
#' @return y - predict of the phenotypes
#' @examples
#'
#'
#' @details
#' \code{iGessPredict} predict the output of the given X and Covariates
#'
#' @export
iGessPredict <- function(fit_, X, Z = NULL) {
    .Call('IGESS_iGessPredict', PACKAGE = 'IGESS', fit_, X, Z)
}

